auth_store: ".harair/auth.json"
default_timeout_sec: 120
skopeo_path: "skopeo"
helm_path: "helm"
oras_path: "oras"

registries:
  harbor1:
    url: "harbor1.local"
    insecure: true
  harbor3:
    url: "harbor3.public.example"
    insecure: false
  harbor2:
    url: "harbor2.local"
    insecure: true

access_control:
  harbor3:
    enable:
      type: "ssh"
      host: "reverse-proxy.public.example"
      user: "ops"
      cmd: "sudo systemctl start nginx"
    disable:
      type: "ssh"
      host: "reverse-proxy.public.example"
      user: "ops"
      cmd: "sudo systemctl stop nginx"
